apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-mfa
spec:
  selector:
    matchLabels:
      app: nodejs-mfa
  template:
    metadata:
      labels:
        app: nodejs-mfa
    spec:
      containers:
      - name: nodejs-mfa
        image: mfa:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        # Expose the metrics endpoint for Prometheus scraping
        livenessProbe:
          httpGet:
            path: /metrics
            port: 3000
        readinessProbe:
          httpGet:
            path: /metrics
            port: 3000
        imagePullPolicy: Never
        
